IDIR =../include
CC=g++
CFLAGS=-I $(IDIR)


	

niftiHeaderTest: niftiHeaderTest.cpp ../src/NiftiOneImageHeader.cpp
	g++ -o niftiHeaderTest niftiHeaderTest.cpp ../src/NiftiOneImageHeader.cpp -I../include 
	
